# Generated by Django 5.0.4 on 2024-04-20 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_cryptoalert_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='cryptocurrency',
            new_name='cryptomonnaie',
        ),
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='threshold',
            new_name='prix',
        ),
        migrations.AddField(
            model_name='cryptoalert',
            name='date_de_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cryptoalert',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
    ]
