# Generated by Django 5.0.4 on 2024-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_rename_cryptocurrency_cryptoalert_cryptomonnaie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='date_de_creation',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='cryptomonnaie',
            new_name='cryptocurrency',
        ),
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cryptoalert',
            name='prix',
        ),
        migrations.AddField(
            model_name='cryptoalert',
            name='price_under',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cryptoalert',
            name='price_upper',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
