# Generated by Django 5.0.4 on 2024-04-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_rename_date_de_creation_cryptoalert_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoalert',
            name='price_upper',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
