# Generated by Django 5.0.4 on 2024-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_cryptoalert_price_upper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoalert',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
