# Generated by Django 5.0.4 on 2024-04-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_cryptoalert_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptoalert',
            old_name='price_under',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cryptoalert',
            name='price_upper',
        ),
        migrations.AddField(
            model_name='cryptoalert',
            name='alert_type',
            field=models.CharField(choices=[('above', 'Au-dessus de'), ('below', 'En dessous de')], default='', max_length=10),
        ),
    ]
